INSERT INTO `industrial_sectors` (`name`) VALUES

('Accounting audit and tax'),
('Advertising'),
('Agriculture and agro processing'),
('Aquaculture and mariculture'),
('Arts crafts and design'),
('Asset management'),
('Automotive and automobiles'),
('Banking and capital markets'),
('Capital projects and infrastructure'),
('Catering services'),
('Chemicals'),
('Clothing and textiles'),
('Communications'),
('Construction and materials'),
('Containers and packaging'),
('Delivery services and logistics'),
('Development finance'),
('Defence security and aerospace'),
('Education and training'),
('Electronics'),
('Energy'),
('Engineering'),
('Entertainment'),
('Environment and waste'),
('Financial services'),
('Food Services'),
('Forestry and paper'),
('General and personal services'),
('Government or public services'),
('Healthcare'),
('Hospitality and leisure'),
('Pharmaceuticals and life sciences'),
('ICT Information and Communication Technology'),
('Insurance'),
('Legal Services'),
('Maintenance service and repair'),
('Manufacturing and industrial'),
('Media'),
('Medical technology'),
('Mining and metals'),
('NGO'),
('Oil and gas'),
('Personal and household Goods'),
('Publishing and journalism'),
('Private equity'),
('Public sector entity'),
('Retail and consumer'),
('Social services'),
('Sport'),
('Social services'),
('Technology'),
('Telecommunications'),
('Tourism and leisure'),
('Transportation and logistics'),
('Utilities');
