INSERT INTO `professional_institutions` (`name`) VALUES

('Institute of Chartered Accountants of Nigeria'),
('Chartered Institute of Bankers of Nigeria'),
('Chartered Institute of Taxation of Nigeria'),
('Nigeria Institute of Estate Surveyors and Valuers'),
('Association of General and Private Medical Practitioners of Nigeria'),
('Association of National Accountants of Nigeria'),
('Business Education Exams Council'),
('Centre for Law and Development'),
('Certified Pension Institute of Nigeria'),
('Chartered Institute of Marketing of Nigeria'),
('Chartered Insurance Institute of Nigeria'),
('Chartered Institute of Personnel Management of Nigeria'),
('Chartered Institute of Stockbrokers'),
('Certified Institute of Cost Management'),
('Medical and Dental Consultants Association of Nigeria'),
('Nigeria Bar Association'),
('Nigerian Institute of Management'),
('Nigeria Institute of Quantity Surveyors'),
('Nigerian Institute of Social and Economic Research'),
('Nigerian Institute of Town Planners'),
('Nigerian Medical Association'),
('Nigerian Society of Engineers'),
('Science Teachers Association of Nigeria'),
('Strategic Management Centre'),
('West African College of Physicians'),
('Institute of Directors'),
('Advertising Practioners Council of Nigeria'),
('Outdoor Advertising Association of Nigeria'),
('Manufacturers Association of Nigeria'),
('The Nigerian Institute of Safety Professionals'),
('Nigerian Institute of Public Relations NIPR'),
('Pharmacist Council of Nigeria'),
('West African Institute for Financial and Economic Management'),
('Financial Institutions Training Centre FITC'),
('Money Market Association of Nigeria'),
('African Institute for Applied Economics'),
('Nigeria Computer Society'),
('Institute of Credit and Risk Managment'),
('Portfolio and Debt Management Institute'),
('Institute of Chartered Economists of Nigeria'),
('Association of National Accountants of Nigeria'),
('Institute of Registered Administrative Managers of Nigeria'),
('The Institute of Certified Geographers of Nigeria'),
('The Institute of Business Development'),
('The Institute of Benefits and Trusts Management'),
('The Institute of Pensions Management'),
('Chartered Institute of Administration'),
('Nigerian Institute of Professional Secretaries'),
('Pipeline Professionals Association of Nigeria PLAN'),
('National Teachers Institute'),
('Nigeria Institute of Public Relations'),
('Pharmaceutical Society of Nigeria'),
('The Institute of Chartered Secretaries of Nigeria'),
('Council for the Regulation of Engineering in Nigeria COREN'),
('Nigerian Institute of Architects'),
('Nigeria Insurers Association'),
('Nigerian Institute of Building'),
('Nigeria Computer Society'),
('Information Technology Association of Nigeria'),
('Certified Institute of Warehousing and Materials Management'),
('Institute of Certified Public Accountants of Nigeria'),
('Certified Pension Institute of Nigeria'),
('Money Market Association of Nigeria'),
('Institute of Chartered Economists of Nigeria'),
('Institute of Forensic Accountants of Nigeria'),
('Chartered Institute of Cost and Management Accountants of Nigeria'),
('The Institute of Credit Administration of Nigeria'),
('The Institute of Company and Commercial Accountants of Nigeria'),
('The Institute of Registered Administrative Managers of Nigeria'),
('The Chartered Institute of Purchasing and Supply'),
('Institute of Industrial Security and Safety of Nigeria'),
('Institute of Public Analysts of Nigeria'),
('Institute of Investment Management and Research'),
('Nigerian Institute of Safety Professionals NISP'),
('Institute of Public Management Unique'),
('Institute of Fraud Examiners'),
('Nigerian Institute of Industrial Management'),
('Medical and Dental Council of Nigeria'),
('Association of West African Professional Economists Bodies'),
('Institute of Strategic Management of Nigeria'),
('Institute of Professional Recruitment Consultants IPRC Nigeria'),
('Institute of Finance and Control of Nigeria'),
('The Chartered Institute of Logistics and Transport'),
('Institute of Treasury Management'),
('The Chartered institute of Purchasing and supply management of Nigeria'),
('Chartered Institute of Commerce of Nigeria'),
('Nigeria Institute of Civil Engineers'),
('Institute of Data Processing Management of Nigeria'),
('Society of Construction Industry Arbitrators of Nigeria'),
('Chartered Institute of Management Accountants CIMA Nigeria');
