INSERT INTO `secondary_subjects` (`name`) VALUES

('Agricultural science'),
('Animal husbandry'),
('Applied electricity or basic electricity'),
('Auto body repairs and spray painting'),
('Auto electrical work'),
('Auto mechanical work'),
('Auto mechanics'),
('Auto parts merchandising'),
('Basketry'),
('Biology'),
('Blocklaying, bricklaying and concreting'),
('Book keeping'),
('Building construction'),
('Business management'),
('Capentry and joinery'),
('Catering craft practice'),
('Ceramics'),
('Chemistry'),
('Christian religious studies'),
('Civic education.doc'),
('Clerical office duties'),
('Clothing  and textiles'),
('Commerce'),
('Computer studies'),
('Cosmetology'),
('Crop  husbandry  and  horticulture'),
('Data processing'),
('Dyeing & bleaching'),
('Economics'),
('Edo'),
('Efik'),
('Electrical installation and maintenance work'),
('Electronics or basic electronics'),
('English language'),
('Financial accounting'),
('Financial accounts'),
('Fisheries alt A'),
('Fisheries alt B'),
('Foods and nutrition'),
('Forestry'),
('French'),
('Furniture making'),
('Further mathematics or mathematics elective'),
('Garment making'),
('General  agriculture'),
('General  knowledge in art'),
('General mathematics or mathematics core'),
('Geography'),
('Ghanaian languages'),
('Government'),
('Graphic design'),
('Gsm phones maintenance and repairs'),
('Hausa'),
('Health education or health science'),
('History'),
('Home management'),
('Ibibio'),
('Igbo'),
('Information and communication technology core'),
('Information and communication technology elective'),
('Insurance'),
('Integrated  science'),
('Islamic religious studies'),
('Jewellery'),
('Leather goods'),
('Leatherwork.docx'),
('Literature in english'),
('Machine woodworking'),
('Marketing'),
('Metalwork'),
('Mining'),
('Music syllabus'),
('Music'),
('Office practice'),
('Painting and decorating'),
('Photography.'),
('Physical education'),
('Physics'),
('Picture making'),
('Plumbing and pipe fitting'),
('Principles of cost accounting'),
('Printing craft practice'),
('Radio,television and electronics works'),
('Refrigeration and air conditioning'),
('Salesmanship'),
('Sculpture'),
('Social studies'),
('Store keeping'),
('Store management'),
('Technical drawing'),
('Textiles'),
('Tourism'),
('Typewriting'),
('Upholstery'),
('Visual art'),
('Welding and fabrication engineering craft practice'),
('West african traditional religion'),
('Woodwork to i.e.d'),
('Woodwork'),
('Yoruba');
