
INSERT INTO `tertiary_institutions` (`name`, `tertiary_types_id`) VALUES

-- College of Agriculture
('College of Agriculture DAC Kabba', 1),
('Federal College of Agriculture Akure', 1),
('Federal College of Agriculture Dadinkowa', 1),
('Federal College of Agriculture Ibadan, Oyo State.', 1),
('Federal College of Agriculture Ishiagu, Ebonyi State.', 1),
('Federal College of Animal Health and Production Technology Ibadan', 1),
('Federal College of Animal Health and Production Technology Vom', 1),
('Federal College of Fisheries and Marine Technology Lagos', 1),
('Federal College of Freshwater Fisheries Technology Baga', 1),
('Federal College of Freshwater Fisheries Technology New Bussa', 1),
('Federal College of Forestry Mechanisation Afaka', 1),
('Federal College of Land Resources Technology Kuru', 1),
('Federal College of Land Resources Technology Owerri', 1),
('Federal College of Wildlife Management New Bussa', 1),
('Federal College of Forestry Ibadan', 1),
('Federal College of Forestry Jos', 1),
('Samaru College of Agriculture DAC Zaria', 1),
('Adamawa State College of Agriculture Mubi', 1),
('Akperan Orshi College of Agriculture Yandev Gboko', 1),
('Akwa Ibom State College of Agriculture Obio-Akpa', 1),
('Anambra State College of Agriculture, Igbariam', 1),
('Audu Bako School of Agriculture Danbatta', 1),
('College of Agriculture Jalingo', 1),
('College of Agriculture Lafia', 1),
('College of Agriculture Zuru', 1),
('Edo State College of Agriculture Iguariakhi', 1),
('Jigawa State College of Agriculture Hadejia', 1),
('Mohamet Lawan College of Agriculture Maiduguri Borno State', 1),
('Niger State College of Agriculture Mokwa', 1),
('Oyo State College of Agriculture Oyo', 1),
('Plateau State College of Agriculture Garkawa', 1),
('Regional Agricultural Training School Maiduguri', 1),
('Rivers State Institute of Agricultural Research and Training Onne', 1),
('School of Agriculture Ikorodu', 1),
('Yobe State College of Agriculture Gujba', 1),
('Zamfara State College of Agriculture Bakura', 1),

-- College of Education
('Federal College of Education Technical Asaba', 2),
('Federal College of Education Kano', 2),
('Federal College of Education Special Oyo', 2),
('Federal College of Education Abeokuta', 2),
('Federal College of Education Eha-Amufu', 2),
('Federal College of Education Technical Gombe', 2),
('Federal College of Education Kontagora', 2),
('Federal College of Education Okene', 2),
('Federal College of Education Technical Omoku', 2),
('Federal College of Education Tech Potiskum', 2),
('Alvan Ikoku College of Education Owerri', 2),
('Federal College of Education Technical Akoka', 2),
('Federal College of Education Technical Bichi', 2),
('Federal College of Education Technical Gusau', 2),
('Federal College of Education Katsina', 2),
('Federal College of Education Obudu', 2),
('Adeyemi College of Education Ondo', 2),
('Federal College of Education Pankshin', 2),
('Federal College of Education Yola', 2),
('Federal College of Education Zaria', 2),
('Nigerian Army School of Education NASE Ilorin', 2),
('Federal College of Education T Umunze', 2),
('College of Education Gindiri', 2),
('Adamawa State College of Education Hong', 2),
('Tai Solarin College of Education Ijebu-Ode', 2),
('College of Education Ikere-Ekiti', 2),
('Ebonyi State College of Education Ikwo', 2),
('College of Education Warri', 2),
('FCT College of Education Zuba', 2),
('Osisatech College of Education Enugu', 2),
('Nasarrawa State College of Education Akwanga', 2),
('Isa Kaita College of Education Dutsin-Ma', 2),
('College of Education Ekiadolor-Benin', 2),
('College of Education Gashua Damaturu', 2),
('Kaduna State College of Education Gidan-Waya Kafanchan', 2),
('Osun State College of Education Ilesa', 2),
('Kwara State College of Education Ilorin', 2),
('Kwara State College of Education', 2),
('College of Education katsina-Ala', 2),
('Saadatu Rimi College of Education Kumbotso Kano', 2),
('College of Education Technical Lafiagi', 2),
('Nwafor Orizu College of Education Nsugbe', 2),
('Adeniran Ogunsanya College of Education Otto Ijanikin', 2),
('Emmanuel Alayande College of Education EACOED Oyo', 2),
('College of Education Waka BIU', 2),
('St Augustine College of Education Project Time Lagos', 2),
('Delta State College of Education Agbor', 2),
('Akwa Ibom State College of Education Afahansit', 2),
('Kogi State College of Education Ankpa', 2),
('Adamu Augie College of Education Argungu', 2),
('College of Education Azare', 2),
('Umar Ibn Ibrahim El-Kanemi College of Education Science and Technology Bama', 2),
('College of Education Jalingo', 2),
('Zamfara State College of Education Maru', 2),
('Jigawa State College of Education Gumel', 2),
('Niger State College of Education Minna', 2),
('Rivers College of Education Rumuolumeni', 2),
('Shehu shagari College of Education Sokoto', 2),
('JamaAtu College of Education JACE Kaduna', 2),
('College of Education Arochukwu Abia', 2),
('College of Education Ila-Orangun', 2),
('Michael Otedola College of Prim. Education Lagos', 2),
('Kashim Ibrahim College of Education Maiduguri', 2),
('Delta State College of Physical Education Mosogar', 2),
('Enugu State College of Education Technical Enugu', 2),
('Cross River State College of Education, Akampa', 2),
('Edo State College of Education Igueben', 2),
('Isaac Jasper Boro COE Sagbama', 2),
('Delar College of Education', 2),
('City College of Education Mararaba Gurku', 2),
('Ansar-Ud-Deen College of Education, Isolo', 2),
('Yewa Central College of Education Ayetoro', 2),
('OSISA Technical College of Education Enugu', 2),
('St. Augustine College of Education Lagos', 2),
('African Thinkers Community of Inquiry Enugu', 2),
('Muftau Olanihun College of Education Ibadan', 2),
('Havard Wilson College of Education Aba', 2),
('Muhyideen College of Education Ilorin', 2),
('College of Education Offa', 2),
('Bauchi Institute of Arabic and Islamic Studies Bauchi', 2),
('Corner Stone College of Education lagos', 2),

-- College of Health Technology
('ABU Teaching Hospital Department of Community Medicine CHO Shika Zaria', 3),
('Federal College of Dental Technology Enugu', 3),
('Aminu Kano University Teaching Hospital Kano', 3),
('National Orthopaedic Centre Igbobi Lagos State', 3),
('Institute of Public Health College of Health Sciences OAU Ile- Ife', 3),
('Othman Dan-Fodio University Teaching Hospital Sokoto', 3),
('Nigerian Army Medical Corps and Schools Ojo', 3),
('University College Hospital Ibadan', 3),
('University of Calabar Teaching Hospital Calabar', 3),
('Anambra State School of Health Technology Obosi', 3),
('University Teaching Hospital Lagos', 3),
('Imo State School of Health Technology Amaigbo', 3),
('Bauchi State School of Health Technology Ningi', 3),
('Lagos State School of Public Health Nursing CHO', 3),
('Imo State School of Public Health Nursing CHO Owerri', 3),
('School of Health Technology Aba', 3),
('Rivers State College of Health Sciences and Technology Port Harcourt', 3),
('School of Health Technology Alushi Via Akwanga', 3),
('School of Health Technology Akure', 3),
('School of Health Technology Calabar', 3),
('School of Health Technology Benin-City Edo State', 3),
('School of Health Technology Elesa', 3),
('School of Health Technology Daura', 3),
('School of Health Technology Idah', 3),
('School of Health Technology Etinan', 3),
('School of Health Technology Ilese Ijebu-Ode', 3),
('School of Health Technology Ijero-Elati', 3),
('School of Health Technology Jahun', 3),
('School of Health Technology Inyi', 3),
('School of Health Technology Kaltungo', 3),
('School of Health Technology Jega', 3),
('School of Health Technology Kano', 3),
('School of Health Technology Kankia', 3),
('School of Health Technology Makurdi', 3),
('School of Health Technology Maiduguri', 3),
('School of Health Technology Mubi', 3),
('School of Health Technology Minna', 3),
('School of Health Technology Ofuoma Ughelli', 3),
('School of Health Technology Offa', 3),
('School of Health Technology Pankshin', 3),
('School of Health Technology Oji River', 3),
('School of Health Technology Tungar Magajiya Kontagora', 3),
('School of Health Technology Takum', 3),
('School of Health Technology Zawan-Jos', 3),
('School of Health Technology Yaba', 3),
('School of Hygiene Kano', 3),
('School of Hygiene Eleyele Ibadan', 3),
('Shehu Idris College of Health Sciences and Technology Makarfi', 3),
('School of Public Health Nursing Nsukka Enugu', 3),
('NKST College of Health Technology Mkar Gboko', 3),
('Sultan Abdur-Rahman School of Health Technology Gwadabawa', 3),

-- Monotechnics
('Accounting audit and tax', 4),
('Advertising', 4),
('Agriculture and agro processing', 4),
('Aquaculture and mariculture', 4),
('Arts crafts and design', 4),
('Asset management', 4),
('Automotive and automobiles', 4),
('Banking and capital markets', 4),
('Capital projects and infrastructure', 4),
('Catering services', 4),
('Chemicals', 4),
('Clothing and textiles', 4),
('Communications', 4),
('Construction and materials', 4),
('Containers and packaging', 4),
('Delivery services and logistics', 4),
('Development finance', 4),
('Defence security and aerospace', 4),
('Education and training', 4),
('Electronics', 4),
('Energy', 4),
('Engineering', 4),
('Entertainment', 4),
('Environment and waste', 4),
('Financial services', 4),
('Food Services', 4),
('Forestry and paper', 4),
('General and personal services', 4),
('Government or public services', 4),
('Healthcare', 4),
('Hospitality and leisure', 4),
('Pharmaceuticals and life sciences', 4),
('ICT  Information and Communication Technology', 4),
('Insurance', 4),
('Legal Services', 4),
('Maintenance service and repair', 4),
('Manufacturing and industrial', 4),
('Media', 4),
('Medical technology', 4),
('Mining and metals', 4),
('NGO', 4),
('Oil and gas', 4),
('Personal and household Goods', 4),
('Publishing and journalism', 4),
('Private equity', 4),
('Public sector entity', 4),
('Retail and consumer', 4),
('Social services', 4),
('Sport', 4),
('Social services', 4),
('Technology', 4),
('Telecommunications', 4),
('Tourism and leisure', 4),
('Transportation and logistics', 4),
('Utilities', 4),

-- Polytechnics
('Akanu Ibiam Federal Polytechnic Unwana', 5),
('Auchi Polytechnic Auchi', 5),
('Federal Polytechnic Ado Ekiti', 5),
('Federal Polytechnic Bali', 5),
('Federal Polytechnic Bauchi', 5),
('Federal Polytechnic Bida', 5),
('Federal Polytechnic Damaturu', 5),
('Federal Polytechnic Ede', 5),
('Federal Polytechnic Ekowe', 5),
('Federal Polytechnic Idah', 5),
('Federal Polytechnic Ilaro', 5),
('Federal Polytechnic Ile-Oluji', 5),
('Federal Polytechnic Kaura Namoda', 5),
('Federal Polytechnic Mubi', 5),
('Federal Polytechnic Nasarawa', 5),
('Federal Polytechnic Nekede', 5),
('Federal Polytechnic Offa', 5),
('Federal Polytechnic Oko', 5),
('Federal Polytechnic of Oil and Gas Bonny', 5),
('Federal Polytechnic Ukana', 5),
('Hussaini Adamu Federal Polytechnic', 5),
('Kaduna Polytechnic', 5),
('National Institute of Construction Technology Uromi', 5),
('Waziri Umaru Federal Polytechnic', 5),
('Yaba College of Technology', 5),
('Abdu Gusau Polytechnic', 5),
('Abia State Polytechnic', 5),
('Abraham Adesanya Polytechnic', 5),
('Abubakar Tatara Ali Polytechnic', 5),
('Adamawa State Polytechnic', 5),
('Akwa Ibom State Polytechnic', 5),
('Bayelsa State College of Arts and Science', 5),
('Benue State Polytechnic', 5),
('DS Adegbenro ICT Polytechnic,', 5),
('Delta State Polytechnic Ogwashi-Uku', 5),
('Delta State Polytechnic Otefe Oghara', 5),
('Delta State Polytechnic Ozoro', 5),
('Edo State Institute of Techology & Management', 5),
('Gateway Polytechnic Saapade', 5),
('Hassan Usman Katsina Polytechnic', 5),
('Imo State Polytechnic, Umuagwo', 5),
('IMT Enugu, Enugu State', 5),
('Jigawa State Polytechnic', 5),
('Kano State Polytechnic', 5),
('Kogi State Polytechnic', 5),
('Kwara State Polytechnic', 5),
('Lagos State Polytechnic', 5),
('Mai Idris Alooma Polytechnic', 5),
('Moshood Abiola Polytechnic', 5),
('Nasarawa State Polytechnic,', 5),
('Niger State Polytechnic,', 5),
('Nuhu Bamalli Polytechnic', 5),
('Ogun State Institute of Technology Igbesa ', 5),
('Osun State College of Technology', 5),
('Osun State Polytechnic', 5),
('Plateau State Polytechnic', 5),
('Ramat Polytechnic', 5),
('Rivers State College of Arts & Science', 5),
('Rivers State Polytechnic', 5),
('Rufus Giwa Polytechnic', 5),
('Sokoto State Polytechnic', 5),
('Taraba State Polytechnic', 5),
('The Ibarapa Polytechnic Eruwa', 5),
('The Oke-Ogun Polytechnic Saki', 5),
('The Polytechnic Ibadan', 5),
('Allover Central Polytechnic', 5),
('Bolmor Polytechnic', 5),
('College of Technology Iresi', 5),
('Covenant Polytechnic', 5),
('Crown Polytechnic', 5),
('Dorben Polytechnic', 5),
('Eastern Polytechnic Port Harcourt', 5),
('Fidei Polytechnic Gboko', 5),
('Grace Polytechnic Surulere', 5),
('Heritage Polytechnic', 5),
('Ibadan City Polytechnic', 5),
('Igbajo Polytechnic', 5),
('Interlink Polytechnic Ijebu Jesa', 5),
('Kalac Chrystal Polytechnic', 5),
('Kings Polytechnic Ubiaja', 5),
('Lagos City Polytechnic Ikeja', 5),
('Lighthouse Polytechnic Evbuobanosa', 5),
('Nacabs Polytechnic Akwanga', 5),
('Nogak Polytechnic Ikom', 5),
('Our Saviour Institute of Science Agric and Technology Enugu', 5),
('Ronik Polytechnic', 5),
('Shaka Polytechnic', 5),
('St Mary Polytechnic Kwamba', 5),
('Temple Gate Polytechnic Aba', 5),
('The Polytechnic Igbo Owu', 5),
('The Polytechnic Ile Ife', 5),
('The Polytechnic Imesi-Ile', 5),
('Tower Polytechnic Ibadan', 5),
('Uyo City Polytechnic', 5),
('Wolex Polytechnic', 5),

-- Technical College
('FSTC Ohanso', 6),
('FSTC Uyo', 6),
('FSTC Otukpo', 6),
('FSTC Lassa', 6),
('FSTC Kafanchan', 6),
('FSTC Zuru', 6),
('FSTC Yaba', 6),
('FSTC Kuta', 6),
('FSTC Ijebu Mushin', 6),
('FSTC Ilesha', 6),
('FSTC Jalingo', 6),
('FSTC Orozo', 6),
('FSTC Tungbo', 6),
('FSTC Ikare Akoko', 6),
('FSTC Uromi', 6),
('FSTC Michika', 6),
('FSTC Usi', 6),
('FSTC Awka', 6),
('FSTC Ahoada', 6),
('Aba Boys Technical College', 6),
('Aba Girls Tech College Ania', 6),
('Government Technical College Yola', 6),
('Government Technical College Ikot Ada Idem', 6),
('Community Technical College Ikot Akata', 6),
('Government Technical College Abak', 6),
('Union Technical College Ikpa Eket', 6),
('Government Technical College Onitsha', 6),
('Government Technical College Gadau', 6),
('Government Technical College Gumau', 6),
('Government Technical College Ekowe', 6),
('Government Technical College Makurdi', 6),
('Government Technical College Bama', 6),
('Government Girls Technical College Damboa', 6),
('Community Technical College Ikot Effanga Mkpa', 6),
('Government Technical College Ogoja', 6),
('St Patrick’s Technical College Ugep', 6),
('Bendi Technical College Bendi', 6),
('Government Technical College Issele-Uku', 6),
('Government Technical College Otogor Ughelli', 6),
('Government Technical College Ozoro', 6),
('Utagbe-Ogbe Technical College Kwale', 6),
('Government Technical College Agbor', 6),
('Government Technical College Sapele', 6),
('Government Technical College Abakaliki', 6),
('Government Technical College Afikpo', 6),
('Government Technical College Afuze', 6),
('Government Technical College Benin-City', 6),
('Government Technical College Igarra', 6),
('Government Technical College Enugu', 6),
('Government Technical College Nsukka', 6),
('Government Technical College Ado-Ekiti', 6),
('Government Technical College Otun Ekiti', 6),
('Government Technical College Ijero', 6),
('Government Technical College Ikole', 6),
('Government Technical College Kumo', 6),
('Ahiara Technical College Ahiazu', 6),
('Osu Technical College Okohia Mbano', 6),
('Okporo Technical College Orlu', 6),
('Government Technical College Owerri', 6),
('Government Technical College Malali', 6),
('Government Technical College Kano', 6),
('Government Technical College Wudil', 6),
('Government Technical College Bagauda', 6),
('Government Technical College Ungogo', 6),
('Government Commercial College Mai Adua', 6),
('Government Technical College Charanchi', 6),
('Government Technical College Funtua', 6),
('Government Technical College Ingawa', 6),
('Government Technical College Mashi', 6),
('Government Technical College Bunza', 6),
('Government Technical College Zuru', 6),
('Government Technical College Mopa', 6),
('Government Technical College Oboroke', 6),
('Government Technical College Ankpa', 6),
('Government Technical College Odu Dekina', 6),
('Government Technical College Idah', 6),
('Government Technical College Esie-Illudun', 6),
('Government Technical College Ilorin', 6),
('Government Technical College Patigi', 6),
('Government Technical College Erin-Ile', 6),
('Amodu Osungbolu Technical College', 6),
('Government Technical College Ado-Soba', 6),
('Government Technical College Ikorodu', 6),
('Industrial Manpower Dev Centre Odomola Ekpe', 6),
('Government Technical College Ikotun', 6),
('Government Technical College Mushin', 6),
('Government Technical College Minna', 6),
('Government Technical College Iyagi Bida', 6),
('Government Technical College New Bussa', 6),
('Government Technical College Kontagoro', 6),
('Suleiman Barau Technical College Suleja', 6),
('Government Technical College Asakio', 6),
('Government Technical College Okitipupa', 6),
('Government Technical College Owo', 6),
('Government Technical College Iwaro-Oka', 6),
('Government Technical College Idi Aba Abeokuta', 6),
('Government Technical College Ijebu-Ode', 6),
('Government Technical College Igbesa', 6),
('Government Technical College Ajegunle', 6),
('Government Technical College Ijebu-Igbo', 6),
('Government Technical College Ilara-Remo', 6),
('Government Technical College Ayetoro', 6),
('Government Technical College Ile-Ife', 6),
('Government Technical College Oshogbo', 6),
('Government Technical College Ilesha', 6),
('Government Technical College Oyo', 6),
('Government Technical College Ogbomosho', 6),
('Government Technical College Igbo-Ora', 6),
('Government Technical College Saki', 6),
('Government Technical College Agodi Ibadan', 6),
('Prospect Continuing Education Centre Ibadan', 6),
('Government Technical College Bukuru', 6),
('Government Technical College Port-Harcourt', 6),
('Government Technical College Ahoad Ele-Ogu', 6),
('Government Technical College Tombia', 6),
('Government Technical College Farfaru', 6),
('Government Technical College Runjin Sambo', 6),
('Government Technical CollegeBinji', 6),
('Government Technical College Geidam', 6),
('Government Technical College Kaura Namoda', 6),
('Government Technical College Mubi', 6),
('Government Technical College Numan', 6),
('Government Technical College Soba', 6),
('Government Technical College Kajuru', 6),
('Government Commercial College Zaria', 6),
('Government Commercial College Makarfi', 6),
('Government Technical College Gembu', 6),
('Government Technical College Bali', 6),
('Government Technical College Takum', 6),
('Don Bosco Training Center Onitsha', 6),
('Folk Tech. College Ikwo', 6),
('Don Bosco Training Inst. Ondo', 6),

-- Universities
('Abubakar Tafawa Balewa University Bauchi', 7),
('Adeyemi University of Education Ondo', 7),
('Ahmadu Bello University Zaria', 7),
('Alvan Ikoku University of Education Owerri', 7),
('Bayero University Kano', 7),
('Federal University Gashua', 7),
('Federal University of Education Kano', 7),
('Federal University of Education Zaria', 7),
('Federal University of Health Sciences Otukpo', 7),
('Federal University of Petroleum Resources Effurun', 7),
('Federal University of Technology Akure', 7),
('Federal University of Technology Minna.', 7),
('Federal University of Technology Owerri', 7),
('Federal University Dutse Jigawa State', 7),
('Federal University Dutsin-Ma Katsina', 7),
('Federal University Kashere, Gombe State', 7),
('Federal University Lafia Nasarawa State', 7),
('Federal University Lokoja Kogi State', 7),
('Federal University Ndufu-Alike Ebonyi State', 7),
('Federal University Otuoke Bayelsa', 7),
('Federal University Oye-Ekiti Ekiti State', 7),
('Federal University Wukari Taraba State', 7),
('Federal University Birnin Kebbi', 7),
('Federal University Gusau.', 7),
('Michael Okpara University of Agric Umudike', 7),
('Modibbo Adama University of Technology Yola', 7),
('National Open University of Nigeria Lagos', 7),
('Nigeria Maritime University, Okerenkoko', 7),
('Nigeria Police Academy Wudil', 7),
('Nigerian Defence Academy Kaduna', 7),
('Nnamdi Azikiwe University Awka', 7),
('Obafemi Awolowo UniversityIle-Ife', 7),
('University of Abuja Gwagwalada', 7),
('University of Agriculture Abeokuta', 7),
('University of Agriculture Makurdi', 7),
('University of Benin', 7),
('University of Calabar', 7),
('University of Ibadan', 7),
('University of Ilorin', 7),
('University of Jos', 7),
('University of Lagos', 7),
('University of Maiduguri', 7),
('University of Nigeria, Nsukka', 7),
('University of Port-Harcourt', 7),
('University of Uyo', 7),
('Usumanu Danfodiyo University', 7),
('Abia State University Uturu', 7),
('Adamawa State University Mubi', 7),
('Adekunle Ajasin University Akungba', 7),
('Akwa Ibom State University Ikot Akpaden Uyo', 7),
('Ambrose Alli University Ekpoma', 7),
('Anambra State University of Science and Technology Uli', 7),
('Bauchi State University Gadau', 7),
('Benue State University Makurdi', 7),
('Bukar Abba Ibrahim University Damaturu', 7),
('Cross River State University of Science and Technology Calabar', 7),
('Delta State University Abraka', 7),
('Ebonyi State University Abakaliki', 7),
('Ekiti State University', 7),
('Enugu State University of Science and Technology Enugu', 7),
('Gombe State Univeristy Gombe', 7),
('Ibrahim Badamasi Babangida University Lapai', 7),
('Ignatius Ajuru University of Education Rumuolumeni', 7),
('Imo State University Owerri', 7),
('Jigawa State University', 7),
('Kaduna State University Kaduna', 7),
('Kano University of Science and Technology Wudil', 7),
('Kebbi State University Kebbi', 7),
('Kogi State University Anyigba', 7),
('Kwara State University Ilorin', 7),
('Ladoke Akintola University of Technology Ogbomoso', 7),
('Lagos State University Ojo Lagos.', 7),
('Nasarawa State University Keffi', 7),
('Niger Delta Unversity Yenagoa', 7),
('Northwest University Kano', 7),
('Olabisi Onabanjo University Ago-Iwoye', 7),
('Ondo State University of Science and Technology, Okitipupa', 7),
('Ondo State Unversity of Medical Sciences', 7),
('Osun State University Oshogbo', 7),
('Plateau State University Bokkos', 7),
('Rivers State University of Science and Technology', 7),
('Sokoto State University Sokoto', 7),
('Tai Solarin Univ. of Education Ijebu-Ode', 7),
('Taraba State University Jalingo', 7),
('Technical University Ibadan', 7),
('Umaru Musa YarAdua University Katsina', 7),
('Achievers University Owo', 7),
('Adeleke University Ede', 7),
('Afe Babalola University Ado-Ekiti', 7),
('African University of Science and Technology Abuja', 7),
('Ajayi Crowther University Ibadan', 7),
('Al-Hikmah University Ilorin', 7),
('Al-Qalam University, Katsina', 7),
('American University of Nigeria Yola', 7),
('Augustine University', 7),
('Babcock University Ilishan-Remo', 7),
('Baze University', 7),
('Bells University of Technology Otta', 7),
('Benson Idahosa University Benin City', 7),
('Bingham University New Karu', 7),
('Bowen University Iwo', 7),
('Caleb University Lagos', 7),
('Caritas University Enugu', 7),
('CETEP City University Lagos', 7),
('Chrisland University', 7),
('Christopher University', 7),
('Covenant University Ota', 7),
('Crawford University Igbesa', 7),
('Crescent University', 7),
('Edwin Clark University Kaigbodo', 7),
('Elizade University Ilara-Mokin', 7),
('Evangel University Akaeze', 7),
('Fountain Unveristy Oshogbo', 7),
('Godfrey Okoye University Ugwuomu-Nike', 7),
('Gregory University Uturu', 7),
('Hallmark University', 7),
('Hezekiah University Umudi', 7),
('Igbinedion University Okada', 7),
('Joseph Ayo Babalola University Ikeji-Arakeji', 7),
('Kings University', 7),
('Kwararafa University Wukari', 7),
('Landmark University Omu-Aran.', 7),
('Lead City University Ibadan', 7),
('Madonna University Okija', 7),
('Mcpherson University Seriki Sotayo Ajebo', 7),
('Micheal and Cecilia University', 7),
('Mountain Top University', 7),
('Nigerian-Turkish Nile University Abuja', 7),
('Novena University Ogume', 7),
('Obong University Obong Ntak', 7),
('Oduduwa University Ipetumodu', 7),
('Pan-African University Lagos', 7),
('Paul University, Awka ', 7),
('Redeemers University Mowe', 7),
('Renaissance University Enugu', 7),
('Rhema University Obeama-Asa ', 7),
('Ritman University', 7),
('Salem University Lokoja', 7),
('Samuel Adegboyega University Ogwa', 7),
('Southwestern University Oku Owa', 7),
('Summit University', 7),
('Tansian UniversityUmunya', 7),
('University of Mkar Mkar', 7),
('Veritas University', 7),
('Wellspring University Evbuobanosa - Edo State', 7),
('Wesley Univ of Science and Tech Ondo', 7),
('Western Delta University Oghara', 7);
