INSERT INTO `tertiary_courses` (`name`, `tertiary_types_id`) VALUES


-- College of Agriculture


-- College of Education
('Biology', 2),
('Chemistry', 2),
('Computer Science', 2),
('Integrated Science', 2),
('Mathematics', 2),
('Physical and Health Education ', 2),
('Human Kinetics', 2),
('Physics', 2),
('Christian Religious Studies', 2),
('Islamic Studies', 2),
('Geography ', 2),
('Social Studies ', 2),
('Economics ', 2),
('History ', 2),
('Literature in English', 2),
('Arabic Language ', 2),
('English Language', 2),
('French Language', 2),
('Hausa Language', 2),
('Igbo Language', 2),
('Yoruba Language', 2),
('Agricultural Education ', 2),
('Business Education', 2),
('Home Economics', 2),
('Technical Education', 2),
('Home Economics', 2),
('Fine and Applied Arts', 2),
('Hearing Impaired', 2),
('Curriculum and Instruction', 2),
('Educational Foundation', 2),
('Educational Psychology', 2),
('General Studies Education', 2),
('Primary Education Studies', 2),
('Political Science Education', 2),
('Gifted and Talented', 2),
('Automobile Technology Education', 2),
('Building Technology Education', 2),
('Electrical/Electronics Technology Education', 2),
('Metalwork Technology Education', 2),
('Woodwork Technology Education', 2),
('Accounting Education', 2),
('Business Education', 2),
('Office Education', 2),

-- College of Health Technology


-- College of Monotechnic


-- College of Polytechnic

-- College of Technical College


-- College of University
('Accounting', 7),
('Actuarial Science', 7),
('African Languages and Literatures', 7),
('Agricultural Economics', 7),
('Agricultural Engineering', 7),
('Agricultural Engineering', 7),
('Agricultural Extension and Rural Sociology', 7),
('Anesthesiology', 7),
('Animal Science', 7),
('Arabic', 7),
('Archaeology', 7),
('Automotive Engineering', 7),
('Bachelor of Architecture', 7),
('Banking and Finance', 7),
('Biochemistry', 7),
('Biochemistry', 7),
('Biological', 7),
('Biology Chemistry', 7),
('Biostatistics', 7),
('Building', 7),
('Business Administration', 7),
('Business Education', 7),
('Ceramics Engineering', 7),
('Chemical Engineering', 7),
('Chemical Pathology', 7),
('Chemistry', 7),
('Christian Religious Studies', 7),
('Civil Engineering', 7),
('Classics', 7),
('Clinical Pharmacology', 7),
('Communication Engineering', 7),
('Community Health', 7),
('Computer', 7),
('Computer Engineering', 7),
('Creative Arts', 7),
('Crop Science', 7),
('Degree', 7),
('Dentistry', 7),
('Dermatovenoreology', 7),
('Economics', 7),
('Educational Administration and Planning', 7),
('Educational Technology', 7),
('Electrical Engineering', 7),
('Electrical/Electronic Engineering', 7),
('Electronic Engineering', 7),
('English', 7),
('English Language and Literature in English', 7),
('Epidemiology', 7),
('Estate Management', 7),
('Farm Power and Machinery', 7),
('Fine Arts', 7),
('Fisheries', 7),
('Food Science and Technology', 7),
('Food Science Technology', 7),
('Forestry', 7),
('Geography', 7),
('Geography', 7),
('Geography', 7),
('Geology', 7),
('Guidance and Counselling', 7),
('Health Education', 7),
('Health Education', 7),
('Health Education', 7),
('Hematology and Blood Transfusion Immunology', 7),
('History', 7),
('History', 7),
('Home Economics', 7),
('Home Economics', 7),
('Human Nutrition', 7),
('Immunology', 7),
('Industrial and Production Engineering', 7),
('Industrial Relations', 7),
('Infections and Tropical Medicine Psychiatry', 7),
('Insurance', 7),
('Integrated Subject', 7),
('Internal Medicine', 7),
('International Law Jurisprudence and legal theory Commercial Law', 7),
('Islamic and Customary Law', 7),
('Islamic Studies', 7),
('Islamic Studies', 7),
('Laboratory Medicine', 7),
('Language Arts', 7),
('Linguistics', 7),
('Management', 7),
('Management Technology', 7),
('Marine Engineering', 7),
('Marketing', 7),
('Mass Communication', 7),
('Materials and Metallurgical Engineering', 7),
('Mathematics', 7),
('Mathematics', 7),
('Mathematics Education', 7),
('Mechanical Engineering', 7),
('Medical Ethics and Jurisprudence', 7),
('Metallurgical Engineering', 7),
('Microbiology', 7),
('Microbiology', 7),
('Mining Engineering', 7),
('Modern European Languages', 7),
('Morbid Anatomy and Forensic Medicine', 7),
('Music', 7),
('Nigerian Languages', 7),
('Obstetrics and Gynecology', 7),
('Optometry', 7),
('Parasitology', 7),
('Pathology', 7),
('Pathophysiology', 7),
('Pediatrics', 7),
('Personnel Management', 7),
('Petro‐Chemical Technology', 7),
('Petroleum Engineering', 7),
('Pharmaceutical Chemistry', 7),
('Pharmaceutical Technology', 7),
('Pharmaceutics', 7),
('Pharmacognosy', 7),
('Pharmacology', 7),
('Pharmacology', 7),
('Pharmacy Administration', 7),
('Philosophy', 7),
('Physical Education', 7),
('Physical Education', 7),
('Physical Education', 7),
('Physics', 7),
('Physics', 7),
('Physiology', 7),
('Political Science', 7),
('Polymer and Textile Technology', 7),
('Polymer Engineering', 7),
('Primary Health', 7),
('Private Law', 7),
('Psychology', 7),
('Public Administration', 7),
('Public Health Engineering', 7),
('Public Law', 7),
('Quantity Surveying', 7),
('Radiology', 7),
('Religious Studies', 7),
('Science', 7),
('Science Education', 7),
('Sciences', 7),
('Social Studies', 7),
('Sociology/Anthropology', 7),
('Sociology/Political Science/Economics', 7),
('Soil and Water Engineering', 7),
('Soil Science', 7),
('Special Education', 7),
('Statistics', 7),
('Structural Engineering', 7),
('Surgery', 7),
('Teacher Education Curriculum Studies', 7),
('Technical Education', 7),
('Theatre Arts', 7),
('Toxicology', 7),
('Urban and Regional Planning (B.Sc) Surveying', 7),
('Veterinary Medicine', 7),
('Vocational Education', 7),
('Water Resources Engineering and Technology', 7),
('Wood Products Engineering', 7),
('Zoology', 7);
